### PR TITLE
CLOUDP-155219: Kubernetes config  generate bug fixes

### LINKED ISSUE #1629: atlas kubernetes ... cli generate manifest issues
Note: I copied most of the bug report from [the issue on mongodb-atlas-kubernetes](mongodb/mongodb-atlas-kubernetes/issues/851) and I changed the description to zoom on atlas cli issues

**What did you do to encounter the bug?**
- create project with default configuration
- create dedicated deployment with default configuration (I did not succeed to import shared deployment due to `diskSizeGB` issue (see in the end of the issue description) )

**What did you expect?**
1. result of command `atlas kubernetes config generate --targetNamespace atlas --projectId <project-id>` when there is deployed a serverless or free tier deployment: I expect to get k8s manifests of project only (without serverless or free tier DB)
2. result of command `atlas kubernetes config generate --targetNamespace atlas --projectId <project-id> --clusterName <cluster-id>`: I expect to get k8s manifests that I can deploy from scratch (as disaster recovery)
3. It would be nice to have a clean output
  - to have no default values or at least to have a toggable option for removal of default values
  - to have no`.metadata.creationTimestamp` / `.status` 

**What happened instead?**
1 . result of command - failure `Error: cluster not found: ServerlessInstance0(63cf7301530d116214820fc4)`
2. result of command - k8s manifests with all values that include:
  - read only attributes which makes an operator to fail to apply the changes (in case of free tier DB)
  - mix of cidrBlock and ipAddress which makes an operator to fail to apply the changes
  - get error related to diskSizeGB (related to free tier DB import)
3. result of command - k8s manifests with all values that include:
  - default values (makes manifest to be big without a reason)
  - irrelevant `.metadata.creationTimestamp` and `.status`

**Operator Information**
 - Operator Version: v1.5.1

**Kubernetes Cluster Information**
- Distribution: k3d
- Version: 1.24.4
- Image Registry location (default docker hub)

**Additional context**

<details><summary>output of atlas cli</summary>

```yaml
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  creationTimestamp: null
  name: poc2
  namespace: atlas
spec:
  alertConfigurations:
  - enabled: true
    eventTypeName: REPLICATION_OPLOG_WINDOW_RUNNING_OUT
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold:
      operator: LESS_THAN
      threshold: "1.000000"
      units: HOURS
  - enabled: true
    eventTypeName: NO_PRIMARY
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 15
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: CLUSTER_MONGOS_IS_MISSING
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 15
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: CONNECTIONS_PERCENT
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "80.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: DISK_PARTITION_SPACE_USED_DATA
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "90.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: QUERY_TARGETING_SCANNED_OBJECTS_PER_RETURNED
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "1000.000000"
      units: RAW
    notifications:
    - delayMin: 10
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: CREDIT_CARD_ABOUT_TO_EXPIRE
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 1440
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: NORMALIZED_SYSTEM_CPU_USER
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "95.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: HOST_HAS_INDEX_SUGGESTIONS
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 10
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: HOST_MONGOT_CRASHING_OOM
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_CONNECTIONS_PERCENT
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "80.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_DATA_SIZE_TOTAL
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "0.750000"
      units: TERABYTES
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_TOTAL_READ_UNITS
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "0.250000"
      units: MILLION_RPU
    notifications:
    - delayMin: 30
      emailEnabled: true
      intervalMin: 720
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_TOTAL_READ_UNITS
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "1.000000"
      units: MILLION_RPU
    notifications:
    - delayMin: 5
      emailEnabled: true
      intervalMin: 120
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: HOST_NOT_ENOUGH_DISK_SPACE
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: SEARCH_MAX_NUMBER_OF_LUCENE_DOCS
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "1.000000"
      units: BILLION
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: JOINED_GROUP
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  auditing:
    auditAuthorizationSuccess: false
    enabled: false
  connectionSecretRef:
    name: ""
  encryptionAtRest:
    awsKms:
      enabled: false
      valid: false
    azureKeyVault:
      enabled: false
    googleCloudKms:
      enabled: false
  maintenanceWindow: {}
  name: poc2
  projectIpAccessList:
  - cidrBlock: 0.0.0.0/0
  settings:
    isCollectDatabaseSpecificsStatisticsEnabled: true
    isDataExplorerEnabled: true
    isPerformanceAdvisorEnabled: true
    isRealtimePerformancePanelEnabled: true
    isSchemaAdvisorEnabled: true
status:
  conditions: []
---
apiVersion: v1
data:
  orgId: ""
  privateApiKey: ""
  publicApiKey: ""
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    atlas.mongodb.com/type: credentials
  name: poc2-credentials
  namespace: atlas
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  creationTimestamp: null
  name: cluster0
  namespace: atlas
spec:
  advancedDeploymentSpec:
    backupEnabled: true
    biConnector:
      enabled: false
      readPreference: secondary
    clusterType: REPLICASET
    encryptionAtRestProvider: NONE
    name: Cluster0
    paused: false
    pitEnabled: false
    replicationSpecs:
    - numShards: 1
      regionConfigs:
      - analyticsSpecs:
          instanceSize: M10
          nodeCount: 0
        autoScaling:
          compute:
            enabled: false
            scaleDownEnabled: false
          diskGB:
            enabled: true
        electableSpecs:
          instanceSize: M10
          nodeCount: 3
        priority: 7
        providerName: GCP
        readOnlySpecs:
          instanceSize: M10
          nodeCount: 0
        regionName: CENTRAL_US
      zoneName: Zone 1
    rootCertType: ISRGROOTX1
    versionReleaseSystem: LTS
  backupRef:
    name: cluster0-backupschedule
    namespace: atlas
  processArgs:
    javascriptEnabled: true
    minimumEnabledTlsProtocol: TLS1_2
    noTableScan: false
  projectRef:
    name: poc2
    namespace: atlas
status:
  conditions: []
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasBackupSchedule
metadata:
  creationTimestamp: null
  name: cluster0-backupschedule
  namespace: atlas
spec:
  export:
    exportBucketId: ""
    frequencyType: ""
  policy:
    name: cluster0-backuppolicy
    namespace: atlas
  referenceHourOfDay: 8
  referenceMinuteOfHour: 26
  restoreWindowDays: 7
status: {}
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasBackupPolicy
metadata:
  creationTimestamp: null
  name: cluster0-backuppolicy
  namespace: atlas
spec:
  items:
  - frequencyInterval: 6
    frequencyType: hourly
    retentionUnit: days
    retentionValue: 2
  - frequencyInterval: 1
    frequencyType: daily
    retentionUnit: days
    retentionValue: 7
  - frequencyInterval: 6
    frequencyType: weekly
    retentionUnit: weeks
    retentionValue: 4
  - frequencyInterval: 40
    frequencyType: monthly
    retentionUnit: months
    retentionValue: 12
status: {}
---

```

</details>

<details><summary>expected output of atlas cli (look for commented out strings)</summary>

```yaml
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  # creationTimestamp: null
  name: poc2
  namespace: atlas
  annotations: # at least it will be good to have it commented in the output of `atlas kubernetes generate ...` output in order not to remove accidentally a project
    mongodb.com/atlas-resource-policy: "keep"
spec:
  alertConfigurations:
  - enabled: true
    eventTypeName: REPLICATION_OPLOG_WINDOW_RUNNING_OUT
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold:
      operator: LESS_THAN
      threshold: "1.000000"
      units: HOURS
  - enabled: true
    eventTypeName: NO_PRIMARY
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 15
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: CLUSTER_MONGOS_IS_MISSING
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 15
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: CONNECTIONS_PERCENT
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "80.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: DISK_PARTITION_SPACE_USED_DATA
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "90.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: QUERY_TARGETING_SCANNED_OBJECTS_PER_RETURNED
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "1000.000000"
      units: RAW
    notifications:
    - delayMin: 10
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: CREDIT_CARD_ABOUT_TO_EXPIRE
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 1440
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: NORMALIZED_SYSTEM_CPU_USER
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "95.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: HOST_HAS_INDEX_SUGGESTIONS
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 10
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: HOST_MONGOT_CRASHING_OOM
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_CONNECTIONS_PERCENT
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "80.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_DATA_SIZE_TOTAL
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "0.750000"
      units: TERABYTES
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_TOTAL_READ_UNITS
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "0.250000"
      units: MILLION_RPU
    notifications:
    - delayMin: 30
      emailEnabled: true
      intervalMin: 720
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_TOTAL_READ_UNITS
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "1.000000"
      units: MILLION_RPU
    notifications:
    - delayMin: 5
      emailEnabled: true
      intervalMin: 120
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: HOST_NOT_ENOUGH_DISK_SPACE
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: SEARCH_MAX_NUMBER_OF_LUCENE_DOCS
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "1.000000"
      units: BILLION
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: JOINED_GROUP
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  # auditing:
  #   auditAuthorizationSuccess: false
  #   enabled: false
  connectionSecretRef:
    name: "mongodb-atlas-operator-api-key" # my changes
  # encryptionAtRest:
  #   awsKms:
  #     enabled: false
  #     valid: false
  #   azureKeyVault:
  #     enabled: false
  #   googleCloudKms:
  #     enabled: false
  # maintenanceWindow: {}
  name: poc2
  projectIpAccessList:
  - cidrBlock: 0.0.0.0/0
  settings:
    isCollectDatabaseSpecificsStatisticsEnabled: true
    isDataExplorerEnabled: true
    isPerformanceAdvisorEnabled: true
    isRealtimePerformancePanelEnabled: true
    isSchemaAdvisorEnabled: true
# status:
#   conditions: []
---
apiVersion: v1
data:
  orgId: ""
  privateApiKey: ""
  publicApiKey: ""
kind: Secret
metadata:
  # creationTimestamp: null
  labels:
    atlas.mongodb.com/type: credentials
  name: poc2-credentials
  namespace: atlas
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  # creationTimestamp: null
  name: cluster0
  namespace: atlas
  annotations: # at least it will be good to have it commented in the output of `atlas kubernetes generate ...` output in order not to remove accidentally a project
    mongodb.com/atlas-resource-policy: "keep"
spec:
  advancedDeploymentSpec:
    backupEnabled: true
    # biConnector:
    #   enabled: false
    #   readPreference: secondary
    clusterType: REPLICASET
    # encryptionAtRestProvider: NONE
    name: Cluster0
    # paused: false
    # pitEnabled: false
    replicationSpecs:
    - numShards: 1
      regionConfigs:
      - analyticsSpecs:
          instanceSize: M10
          nodeCount: 0
        autoScaling:
          compute:
            enabled: false
            scaleDownEnabled: false
          diskGB:
            enabled: true
        electableSpecs:
          instanceSize: M10
          nodeCount: 3
        priority: 7
        providerName: GCP
        readOnlySpecs:
          instanceSize: M10
          nodeCount: 0
        regionName: CENTRAL_US
      zoneName: Zone 1
    rootCertType: ISRGROOTX1
    versionReleaseSystem: LTS
  backupRef:
    name: cluster0-backupschedule
    namespace: atlas
  processArgs:
    javascriptEnabled: true
    minimumEnabledTlsProtocol: TLS1_2
    noTableScan: false
  projectRef:
    name: poc2
    namespace: atlas
# status:
#   conditions: []
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasBackupSchedule
metadata:
  # creationTimestamp: null
  name: cluster0-backupschedule
  namespace: atlas
spec:
  export:
    exportBucketId: ""
    frequencyType: "MONTHLY"
  policy:
    name: cluster0-backuppolicy
    namespace: atlas
  referenceHourOfDay: 8
  referenceMinuteOfHour: 26
  restoreWindowDays: 7
# status: {}
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasBackupPolicy
metadata:
  # creationTimestamp: null
  name: cluster0-backuppolicy
  namespace: atlas
spec:
  items:
  - frequencyInterval: 6
    frequencyType: hourly
    retentionUnit: days
    retentionValue: 2
  - frequencyInterval: 1
    frequencyType: daily
    retentionUnit: days
    retentionValue: 7
  - frequencyInterval: 6
    frequencyType: weekly
    retentionUnit: weeks
    retentionValue: 4
  - frequencyInterval: 40
    frequencyType: monthly
    retentionUnit: months
    retentionValue: 12
# status: {}
---
```

</details>

<details><summary>error of diskSizeGB</summary>

`{"level":"INFO","time":"2023-01-24T07:47:05.189Z","msg":"Status update","atlasdeployment":"atlas/cluster0","lastCondition":{"type":"DeploymentReady","status":"False","lastTransitionTime":null,"reason":"InternalError","message":"json: cannot unmarshal number 0.5 into Go struct field AdvancedDeploymentSpec.diskSizeGB of type int"}}`

</details>

<details><summary>error of cidrBlock and ipAddress together</summary>

`{"level":"INFO","time":"2023-01-24T08:26:29.867Z","msg":"Status update","atlasproject":"atlas/poc2","lastCondition":{"type":"IPAccessListReady","status":"False","lastTransitionTime":null,"reason":"ProjectIPAccessListInvalid","message":"only one of the 'awsSecurityGroup', 'cidrBlock' or 'ipAddress' is required be specified"}}`

</details>

<details><summary>error of backup schedule with unsupported value</summary>

`The AtlasBackupSchedule "cluster0-backupschedule" is invalid: spec.export.frequencyType: Unsupported value: "": supported values: "MONTHLY"`

</details>

### PR DESCRIPTION
**Pull request by Sugar-pack**
## Proposed changes

Fix bug with fields initialisation
Add normaliser for k8s CR names
Add tests

_Jira ticket:_ CLOUDP-155219

Closes #1629 

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [x] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -155,10 +155,15 @@ integration-test: ## Run integration tests
 	@echo "==> Running integration tests..."
 	$(TEST_CMD) --tags="$(INTEGRATION_TAGS)" -count=1 ./internal...
 
+.PHONY: fuzz-normalizer-test
+fuzz-normalizer-test: ## Run fuzz test
+	@echo "==> Running fuzz test..."
+	$(TEST_CMD) -fuzz=Fuzz -fuzztime 50s --tags="$(UNIT_TAGS)" -race ./internal/kubernetes/operator/resources
```
[the remark this answers is not in the document]
Comment (Sugar-pack) [reply Makefile:161]: It's a part of unit tests. Go test -fuzz does not support multipackage testing. That's why I add a new command

[the remark this answers is not in the document]
Comment (gssbzn) [reply Makefile:161]: this is what evergreen runs
https://github.com/mongodb/mongodb-atlas-cli/blob/450429129d5d51837b7eb6f3558a185bfa8a4c0c/build/ci/evergreen.yml#L68-L75

which doesn't include `fuzz-normalizer-test` is this make target something you need to run on evergreen? I suppose you do

[the remark this answers is not in the document]
Comment (Sugar-pack) [reply Makefile:161]: I see. But this test is run in Github actions tests.

**Review by igor-karpukhin — DISMISSED** [review]
Looks good 👍 One note, maybe we should restrict these tests to only run on `cloud-dev` as we plan to also add tests for deployments, @Sugar-pack.

File: Makefile (hunk 1 above)
[the remark this answers is not in the document]
Comment (gssbzn) [reply Makefile:161]: up to you and the kube team, only evergreen tests are mandatory, we have GH actions mainly for easy in case of outside contributions given evergreen is restricted to only mongodb employees

File: internal/kubernetes/operator/dbusers/dbusers.go [hunk 2]
```diff
@@ -28,8 +28,9 @@ import (
 	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 )
 
-func BuildDBUsers(provider store.AtlasOperatorDBUsersStore, projectID, projectName, targetNamespace string, includeSecrets bool) ([]*atlasV1.AtlasDatabaseUser, []*corev1.Secret, error) {
+func BuildDBUsers(provider store.AtlasOperatorDBUsersStore, projectID, projectName, targetNamespace string) ([]*atlasV1.AtlasDatabaseUser, []*corev1.Secret, error) {
 	users, err := provider.DatabaseUsers(projectID, &mongodbatlas.ListOptions{})
+	// TODO: add validator for similar user names
```
Comment (gssbzn) [inline internal/kubernetes/operator/dbusers/dbusers.go:33]: can you please link a CLOUD here

File: internal/kubernetes/operator/deployment/deployment.go [hunk 3]
```diff
@@ -246,14 +248,14 @@ func buildBackups(backupsProvider store.ScheduleDescriber, projectID, clusterNam
 			APIVersion: "atlas.mongodb.com/v1",
 		},
 		ObjectMeta: v1.ObjectMeta{
-			Name:      strings.ToLower(fmt.Sprintf("%s-backupschedule", clusterName)),
+			Name:      resources.NormalizeAtlasResourceName(fmt.Sprintf("%s-backupschedule", clusterName)),
```
Comment (gssbzn) [inline internal/kubernetes/operator/deployment/deployment.go:251]: empirically I feel this reads better and will be better long term 
```suggestion
			Name:      fmt.Sprintf("%s-backupschedule", resources.NormalizeAtlasResourceName(clusterName)),
```

But since this is empirical don't take it as a blocker

File: internal/kubernetes/operator/project/project.go [hunk 4]
```diff
@@ -704,7 +704,7 @@ func buildTeams(teamsProvider store.AtlasOperatorTeamsStore, orgID, projectID, p
 				teamRef.TeamID, projectName, projectID, err)
 		}
 
-		crName := fmt.Sprintf("%s-team-%s", strings.ToLower(projectName), strings.ToLower(team.Name))
+		crName := fmt.Sprintf("%s-team-%s", resources.NormalizeAtlasResourceName(projectName), resources.NormalizeAtlasResourceName(team.Name))
```
Comment (gssbzn) [inline internal/kubernetes/operator/project/project.go:707]: you apply the same transformation to `projectName` multiple times, consider centralizing it and reusing the trnasformed value

File: internal/kubernetes/operator/resources/normalizer.go [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+		".": "dot",
+		"@": "at",
+		"(": "left-parenthesis",
+		")": "right-parenthesis",
+		"&": "and",
+		"+": "plus",
+		":": "colon",
+		",": "comma",
+		"'": "single-quote",
+	}
```
Comment (gssbzn) [inline internal/kubernetes/operator/resources/normalizer.go:37]: let's define this outside the function so it doesn't need to be recreated every-time the function is invoked

File: internal/kubernetes/operator/resources/normalizer.go [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+
+import (
+	"strings"
+
+	"k8s.io/apimachinery/pkg/util/validation"
+)
+
+// NormalizeAtlasResourceName normalizes the name to be used as a resource name in Kubernetes
+// Run fuzzing test if you want to change this function!
+func NormalizeAtlasResourceName(name string) string {
```
Comment (gssbzn) [inline internal/kubernetes/operator/resources/normalizer.go:25]:
```suggestion
func NormalizeAtlasName(name string) string {
```

don't stutter, `resource.NormalizeAtlasName`

**Review by gssbzn — COMMENTED** [review]
left some minor things and also scheduled the k8s test suit since it doesn't run by default on PR to confirm this works as expected https://spruce.mongodb.com/task/mongocli_master_e2e_atlas_clusters_atlas_clusters_e2e_kubernetes_patch_c3724c784b4f10602cb6d90b901e86a7b7d98a4e_63d118355623432d3194d89b_23_01_25_11_53_26/logs?execution=0

File: internal/kubernetes/operator/dbusers/dbusers.go (hunk 2 above)
Comment (Sugar-pack) [reply internal/kubernetes/operator/dbusers/dbusers.go]: Done

File: internal/kubernetes/operator/project/project.go (hunk 4 above)
Comment (Sugar-pack) [reply internal/kubernetes/operator/project/project.go]: Done

Comment (Sugar-pack) [reply internal/kubernetes/operator/project/project.go]: Done

File: internal/kubernetes/operator/resources/normalizer.go (hunk 5 above)
Comment (Sugar-pack) [reply internal/kubernetes/operator/resources/normalizer.go]: Done

File: internal/kubernetes/operator/resources/normalizer.go (hunk 6 above)
Comment (Sugar-pack) [reply internal/kubernetes/operator/resources/normalizer.go]: Done

File: test/e2e/atlas/helper_test.go [hunk 7]
```diff
@@ -394,6 +414,122 @@ func createProject(projectName string) (string, error) {
...
+		args = append(args, "--govCloudRegionsOnly")
+	}
+	cmd := exec.Command(cliPath, args...)
+	cmd.Env = os.Environ()
+	resp, err := cmd.CombinedOutput()
+	if err != nil {
+		return "", fmt.Errorf("%s (%w)", string(resp), err)
+	}
+
+	var project mongodbatlas.Project
```
Comment (gssbzn) [inline test/e2e/atlas/helper_test.go:439]: golint may be in a dirty state, may be a good idea to merge master if you haven't

**Review by gssbzn — DISMISSED** [review]
LGTM pending the [k8s tests](https://spruce.mongodb.com/task/mongocli_master_e2e_atlas_clusters_atlas_clusters_e2e_kubernetes_patch_c3724c784b4f10602cb6d90b901e86a7b7d98a4e_63d22f943627e01c123081f6_23_01_26_07_45_25/logs?execution=0) pass

File: internal/kubernetes/operator/resources/normalizer.go [hunk 8]
```diff
@@ -0,0 +1,70 @@
...
+		" ": "-",
+		".": "dot",
+		"@": "at",
+		"(": "left-parenthesis",
+		")": "right-parenthesis",
+		"&": "and",
+		"+": "plus",
+		":": "colon",
+		",": "comma",
+		"'": "single-quote",
```
Comment (igor-karpukhin) [inline internal/kubernetes/operator/resources/normalizer.go:34]: @Sugar-pack  I think one more character is missing - the underscore: `_`

Comment (Sugar-pack) [reply internal/kubernetes/operator/resources/normalizer.go:34]: Done

**Review by igor-karpukhin — APPROVED** [review]
Good job 👍

**Review by gssbzn — APPROVED** [review]
LGTM if LGTEVG thanks for all the work here
