### PR TITLE
CLOUDP-238932: Validate maxDate and minDate before running command

### LINKED ISSUE #2793: Date range filter not working
**Describe the bug**
Using the command atlas events projects list, the maxDate and minDate filters are not being applied.
The exact command is:
`atlas events projects list --output json --projectId 5ef516da5cc30930bcd83889 --maxDate 2024-03-18T15:00:03+00:00Z --minDate 2024-03-18T14:40:03+00:00Z --limit 500 --page 1`
I try to get event logs of the last 20 mins, but the result is approximately 11 million records.
I changed the minDate to 24 hours ago, and the totalCount is the same.
Also in the response href:
```
"links": [
    {
      "href": "https://cloud.mongodb.com/api/atlas/v2/groups/5ef516da5cc30930bcd83889/events?includeCount=true\u0026includeRaw=false\u0026pageNum=1\u0026itemsPerPage=500",
      "rel": "self"
    },
    {
      "href": "https://cloud.mongodb.com/api/atlas/v2/groups/5ef516da5cc30930bcd83889/events?includeCount=true\u0026includeRaw=false\u0026itemsPerPage=500\u0026pageNum=2",
      "rel": "next"
    }
  ]
```
You can't see the dates in the href, so my best guess is that the CLI is not implementing the filter in the request to the server.

**To Reproduce**
1. Run `atlas events projects list` with the min-max date filter
2. In the response, verify if the totalCount varies and if the href has the dates in the URL

**Expected behavior**
I need the filters to be implemented so I can get only the logs from a certain period of time.

**Desktop (please complete the following information):**
OS:
3.19.1
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.1
PRETTY_NAME="Alpine Linux v3.19"

MongoCLI version [e.g. 1.2]
atlascli version: 1.14.2
git version: https://github.com/mongodb/mongodb-atlas-cli/commit/47dc06c7a9b1183cd8b0027306dd839d8547893d
Go version: go1.21.6
os: linux
arch: amd64
compiler: gc

**Additional context**
Pretty sure we don't produce 11 million logs in 20 minutes, I've been trying to retrieve 11 million logs from your system, and after page 1000, I start getting 500 error timeout, just an FYI

### PR DESCRIPTION
**Pull request by blva**
## Proposed changes

_Jira ticket:_ [CLOUDP-238932](https://jira.mongodb.org/browse/CLOUDP-238932)

closes #2793 

```shell
❯ atlasdev  events projects list --output json --projectId  5efda6aea3f2ed2e7dd6ce05 --maxDate 2024-03-18T15:00:03+00:00Z --minDate 2024-03-18T14:40:03+00:00Z --limit 1 --page 1
Error: parsing time "2024-03-18T15:00:03+00:00Z" as "2006-01-02T15:04:05-0700": cannot parse "+00:00Z" as "-0700", supported timestamp formats examples: 2006-01-02T15:04:05Z07:00, 2006-01-02T15:04:05-0700
```

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

### CODE REVIEW

File: internal/cli/atlas/events/list.go [hunk 1]
```diff
@@ -130,6 +130,22 @@ func (opts *ListOpts) NewProjectListOptions() admin.ListProjectEventsApiParams {
 	return p
 }
 
+func (opts *EventListOpts) ValidateMaxAndMinDates() func() error {
```
Comment (gssbzn) [inline internal/cli/atlas/events/list.go:133]: any reason to not do it directly in the NewOrgListOptions and NewProjectListOptions changing those methods to return the error and checking it instead of assuming it was previously validated?

Comment (gssbzn) [reply internal/cli/atlas/events/list.go:133]: if you feel strongly as a prerequisite can you please add a unit test?

Comment (blva) [reply internal/cli/atlas/events/list.go:133]: nope, no strong opinion here, just seemed logic to do this as pre-run to validate the flag format. I'll update

File: internal/cli/atlas/events/orgs_list.go [hunk 2]
```diff
@@ -56,8 +58,10 @@ func (opts *orgListOpts) Run() error {
 	return opts.Print(r)
 }
 
-func (opts *orgListOpts) NewOrgListOptions() admin.ListOrganizationEventsApiParams {
+func (opts *orgListOpts) NewOrgListOptions() (admin.ListOrganizationEventsApiParams, error) {
```
Comment (gssbzn) [inline internal/cli/atlas/events/orgs_list.go:61]:
```suggestion
func (opts *orgListOpts) NewOrgListOptions() (*admin.ListOrganizationEventsApiParams, error) {
```

File: internal/cli/atlas/events/orgs_list.go [hunk 3]
```diff
@@ -74,13 +78,16 @@ func (opts *orgListOpts) NewOrgListOptions() admin.ListOrganizationEventsApiPara
 	if opts.OmitCount {
 		p.IncludeCount = pointer.Get(false)
 	}
-	if maxDate, err := convert.ParseTimestamp(opts.MaxDate); err == nil {
-		p.MaxDate = pointer.Get(maxDate)
+
+	if p.MaxDate, err = opts.ParseDate(opts.MaxDate); err != nil {
+		return p, err
 	}
```
Comment (gssbzn) [inline internal/cli/atlas/events/orgs_list.go:84]:
```suggestion
	if opts.MaxDate != "" {
		if p.MaxDate, err = opts.ParseDate(opts.MaxDate); err != nil {
			return nil, err
		}
	}
```

File: internal/cli/atlas/events/orgs_list.go [hunk 4]
```diff
@@ -46,8 +45,11 @@ func (opts *orgListOpts) initStore(ctx context.Context) func() error {
 
 func (opts *orgListOpts) Run() error {
 	var r interface{}
```
Comment (gssbzn) [inline internal/cli/atlas/events/orgs_list.go:47]: this can be delete
```suggestion
```

File: internal/cli/atlas/events/orgs_list.go [hunk 5]
```diff
@@ -46,8 +45,11 @@ func (opts *orgListOpts) initStore(ctx context.Context) func() error {
...
-	var err error
-	listEventsAPIParams := opts.NewOrgListOptions()
+
+	listEventsAPIParams, err := opts.NewOrgListOptions()
+	if err != nil {
+		return err
+	}
 	r, err = opts.store.OrganizationEvents(&listEventsAPIParams)
```
Comment (gssbzn) [inline internal/cli/atlas/events/orgs_list.go:53]:
```suggestion
	r, err := opts.store.OrganizationEvents(listEventsAPIParams)
```

File: internal/cli/atlas/events/orgs_list_test.go [hunk 6]
```diff
@@ -44,6 +44,47 @@ func Test_orgListOpts_Run(t *testing.T) {
...
+			MinDate: "2024-03-18T13:00:03+00:00Z",
+		},
+	}
+	listOpts.OrgID = "1"
+
+	if err := listOpts.Run(); err == nil {
+		t.Fatalf("Expected inavlid date error from Run() got none")
+	}
+}
 func TestOrgListBuilder(t *testing.T) {
```
Comment (gssbzn) [inline internal/cli/atlas/events/orgs_list_test.go:88]:
```suggestion
}

func TestOrgListBuilder(t *testing.T) {
```

File: internal/cli/atlas/events/projects_list.go [hunk 7]
```diff
@@ -47,34 +46,38 @@ func (opts *projectListOpts) initStore(ctx context.Context) func() error {
...
 	if err != nil {
 		return err
 	}
 
 	return opts.Print(r)
 }
 
-func (opts *projectListOpts) NewProjectListOptions() admin.ListProjectEventsApiParams {
+func (opts *projectListOpts) NewProjectListOptions() (admin.ListProjectEventsApiParams, error) {
 	var eventType *[]string
```
Comment (gssbzn) [inline internal/cli/atlas/events/projects_list.go:63]: same comments as org events

File: internal/cli/atlas/events/orgs_list.go (hunk 3 above)
Comment (gssbzn) [reply internal/cli/atlas/events/orgs_list.go]: oh I see ParseDate is now empty safe, then this may not be needed

File: internal/cli/atlas/events/list.go [hunk 8]
```diff
@@ -127,7 +142,19 @@ func (opts *ListOpts) NewProjectListOptions() admin.ListProjectEventsApiParams {
 		p.IncludeCount = pointer.Get(false)
 	}
 
-	return p
+	return p, nil
+}
+
+func ParseDate(date string) (*time.Time, error) {
```
Comment (gssbzn) [inline internal/cli/atlas/events/list.go:148]:
```suggestion
func parseDate(date string) (*time.Time, error) {
```
let's make it private

File: internal/cli/atlas/events/list.go [hunk 9]
```diff
@@ -127,7 +142,19 @@ func (opts *ListOpts) NewProjectListOptions() admin.ListProjectEventsApiParams {
...
+	if date == "" {
+		return nil, nil
+	}
+
+	parsedDate, err := convert.ParseTimestamp(date)
+	if err != nil {
+		return nil, err
+	}
+	return pointer.Get(parsedDate), nil
```
Comment (gssbzn) [inline internal/cli/atlas/events/list.go:157]:
```suggestion
	return &parsedDate, nil
```

**Review by gssbzn — APPROVED** [review]
LGTM :shipit:

File: test/e2e/atlas/events_test.go [hunk 10]
```diff
@@ -54,7 +54,7 @@ func TestEvents(t *testing.T) {
 			orgEntity,
 			"list",
 			"--omitCount",
-			"--minDate="+time.Now().Add(-time.Hour*time.Duration(24)).Format("2006-01-02"),
+			"--minDate="+time.Now().Add(-time.Hour*time.Duration(24)).Format("2006-01-02T15:04:05-0700"),
```
Comment (gssbzn) [inline test/e2e/atlas/events_test.go:57]: 🙃
